name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
         submodules: recursive

      
    - name: Install curl lib
      run: |
        sudo apt-get install libcurl4-openssl-dev

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/ingest-tools/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/ingest-tools/build --config ${{env.BUILD_TYPE}}
      
    - name: show build folder
      working-directory: ${{github.workspace}}/ingest-tools/build
      # Build your program with the given configuration
      run: ls -all
      
    - name: Run Unit Test
      working-directory: ${{github.workspace}}/ingest-tools/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ./unittest  
      
    - name: Copy test file tos-096-750k.cmfv
      working-directory: ${{github.workspace}}/ingest-tools/
      run: cp test_files/tos-096-750k.cmfv build/test.cmfv
      
    - name: run fmp4dump
      working-directory: ${{github.workspace}}/ingest-tools/build
      run: ./fmp4dump test.cmfv
      
    - name: run fmp4Init to create init segment
      working-directory: ${{github.workspace}}/ingest-tools/build
      run: ./fmp4Init test.cmfv out_init.cmfv
      
    - name: run fmp4dump with init segment
      working-directory: ${{github.workspace}}/ingest-tools/build
      run: ./fmp4dump out_init.cmfv

